# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testContainer3m1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_69809acafa55459c943187174ec21a2e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c53ea66a6c284c5da6a142a516d9c417 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_69809acafa55459c943187174ec21a2e }}/ghcr.io/s3takuto/container/flask-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testContainer3m1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a5b903891494467dacbd0d35a61cbaf5 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_69809acafa55459c943187174ec21a2e }}/ghcr.io/s3takuto/container/flask-app:${{ github.sha }}'